In [342]:
# Source of dataset : https://www.kaggle.com/jsphyg/weather-dataset-rattle-package

<h1 style="color: purple">Predicting Rainfall for the Next Day</h1>

<p style = "font-size:18px"> This notebooks predicts if it is going to rain tomorrow based on weather conditions of today, using Decision Tree Classifier. <p>

In [371]:
# importing all necessary libraries
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [372]:
data = pd.read_csv('./weatherAUS.csv') # reading the csv file containing data for weather conditions

In [373]:
data.columns # features in the dataset

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [374]:
data[data.isnull().any(axis=1)] # check for NaN values

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes,3.6,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,Yes,0.0,No
14,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,NaN,0.0,No
15,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,No,16.8,Yes
16,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes,10.6,Yes
17,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,0.0,No
18,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No,0.0,No
19,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No,0.0,No
20,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No,0.0,No
21,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No,0.0,No
22,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No,0.0,No
23,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,0.0,No
24,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No,0.0,No
25,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No,0.0,No
26,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No,0.0,No
27,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,No,1.2,Yes
28,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,Yes,0.8,No
29,2008-12-31,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142163,2017-05-26,Uluru,14.3,27.6,0.4,NaN,NaN,WNW,39.0,NaN,...,27.0,1020.5,1016.1,4.0,7.0,16.1,27.2,No,0.0,No
142164,2017-05-27,Uluru,9.3,28.0,0.0,NaN,NaN,W,28.0,SSW,...,16.0,1019.9,1016.9,NaN,NaN,16.6,27.3,No,0.0,No
142165,2017-05-28,Uluru,8.0,24.6,0.0,NaN,NaN,E,33.0,SE,...,25.0,1021.7,1018.8,4.0,NaN,13.8,23.5,No,0.0,No
142166,2017-05-29,Uluru,12.7,22.2,0.0,NaN,NaN,E,37.0,E,...,34.0,1024.3,1021.7,8.0,8.0,13.9,21.0,No,0.0,No
142167,2017-05-30,Uluru,9.4,22.7,0.0,NaN,NaN,E,35.0,SE,...,32.0,1026.6,1023.6,8.0,4.0,11.8,22.3,No,0.0,No
142168,2017-05-31,Uluru,5.4,20.5,0.0,NaN,NaN,E,46.0,E,...,32.0,1029.2,1025.3,NaN,NaN,11.1,20.2,No,0.0,No
142169,2017-06-01,Uluru,5.6,19.4,0.0,NaN,NaN,E,43.0,E,...,22.0,1029.6,1027.1,NaN,NaN,9.7,18.3,No,0.0,No
142170,2017-06-02,Uluru,1.5,19.2,0.0,NaN,NaN,E,37.0,ESE,...,18.0,1030.7,1026.7,NaN,NaN,6.8,17.6,No,0.0,No
142171,2017-06-03,Uluru,3.8,19.8,0.0,NaN,NaN,ENE,39.0,ESE,...,22.0,1028.7,1024.1,NaN,NaN,8.6,18.9,No,0.0,No
142172,2017-06-04,Uluru,4.5,18.8,0.0,NaN,NaN,E,31.0,ESE,...,26.0,1026.9,1022.4,NaN,NaN,9.5,18.6,No,0.0,No
142173,2017-06-05,Uluru,4.9,20.7,0.0,NaN,NaN,E,37.0,ESE,...,11.0,1027.1,1023.9,NaN,NaN,10.3,19.8,No,0.0,No
142174,2017-06-06,Uluru,1.2,20.8,0.0,NaN,NaN,E,43.0,ESE,...,6.0,1029.8,1025.9,NaN,NaN,7.9,19.9,No,0.0,No
142175,2017-06-07,Uluru,0.5,21.7,0.0,NaN,NaN,E,43.0,ESE,...,19.0,1029.0,1025.0,NaN,NaN,9.5,20.5,No,0.0,No
142176,2017-06-08,Uluru,4.0,20.0,0.0,NaN,NaN,SE,39.0,ESE,...,26.0,1030.2,1026.7,NaN,NaN,9.1,19.0,No,0.0,No
142177,2017-06-09,Uluru,3.4,19.8,0.0,NaN,NaN,E,43.0,ESE,...,23.0,1031.8,1027.7,NaN,NaN,8.7,18.9,No,0.0,No
142178,2017-06-10,Uluru,3.2,18.6,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1031.0,1027.2,NaN,NaN,8.2,17.4,No,0.0,No
142179,2017-06-11,Uluru,2.4,19.1,0.0,NaN,NaN,E,33.0,SE,...,24.0,1030.0,1026.2,NaN,NaN,8.0,18.8,No,0.0,No
142180,2017-06-12,Uluru,5.1,19.7,0.0,NaN,NaN,E,46.0,ESE,...,29.0,1028.5,1025.8,NaN,NaN,8.5,19.2,No,0.0,No
142181,2017-06-13,Uluru,2.5,21.2,0.0,NaN,NaN,ENE,35.0,ESE,...,32.0,1027.2,1023.0,NaN,NaN,10.3,20.3,No,0.0,No
142182,2017-06-14,Uluru,2.3,21.4,0.0,NaN,NaN,SE,22.0,SE,...,28.0,1026.9,1022.8,NaN,NaN,8.9,20.3,No,0.0,No
142183,2017-06-15,Uluru,2.6,22.5,0.0,NaN,NaN,S,19.0,S,...,24.0,1025.0,1021.4,NaN,NaN,8.8,22.1,No,0.0,No
142184,2017-06-16,Uluru,5.2,24.3,0.0,NaN,NaN,E,24.0,SE,...,24.0,1023.8,1020.0,NaN,NaN,12.3,23.3,No,0.0,No
142185,2017-06-17,Uluru,6.4,23.4,0.0,NaN,NaN,ESE,31.0,S,...,25.0,1025.8,1023.0,NaN,NaN,11.2,23.1,No,0.0,No
142186,2017-06-18,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No,0.0,No
142187,2017-06-19,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No,0.0,No
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0.0,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No

<p style = "font-size: 18px"> <b>Date</b> and <b>location</b> are deleted since they are not helpful in predicting rainfall for tomorrow </p>

In [375]:
del data['Date']
del data['Location']

In [376]:
data.shape[0] # Number of rows before dropping rows with null values

142193

In [377]:
data = data.dropna() # Dropping rows with null value

In [378]:
data.shape[0] # Number of rows after dropping rows with null values

56420

In [379]:
clean_data = data.copy()
clean_data['RainTomorrow'] = (clean_data['RainTomorrow'] == 'Yes')*1 # Changing 'Yes' to 1
clean_data['RainToday'] = (clean_data['RainToday'] == 'Yes')*1 # Changing 'Yes' to 1

In [380]:
print(clean_data['RainTomorrow'][:5]) # First five values for Rain Tomorrow

5939    0
5940    0
5942    0
5943    0
5944    0
Name: RainTomorrow, dtype: int32

In [387]:
y = clean_data[['RainTomorrow']].copy() # copying values in rain tomorrow to variable y

In [388]:
y.head() # First five values in y

      RainTomorrow
5939             0
5940             0
5942             0
5943             0
5944             0

In [389]:
features = ['WindGustSpeed','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm',
       'Cloud9am', 'Cloud3pm'] # features to be used to predict rainfall for tomorrow

In [390]:
X = clean_data[features].copy() # copying values in features to variable X

In [391]:
X.columns # printing names of features in X

Index(['WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm'],
      dtype='object')

In [392]:
y.columns

Index(['RainTomorrow'], dtype='object')

In [393]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=324) # splitting data for training and testing

In [424]:
rainfall_classifier = DecisionTreeClassifier(max_leaf_nodes=50, random_state=0) # Using Decision Tree Classifier
rainfall_classifier.fit(X_train, y_train) #Training the model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=50,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [425]:
predictions = rainfall_classifier.predict(X_test) # Predicting the model

In [426]:
predictions[:10] # Printing last 10 values predicted

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [422]:
y_test['RainTomorrow'][:10]  # Printing actual last 10 values

74641     0
32517     0
35264     0
120570    0
119334    0
33065     0
117181    0
65181     0
118796    1
82234     1
Name: RainTomorrow, dtype: int32

In [423]:
accuracy_score(y_true = y_test, y_pred = predictions) # Checking accuracy of the model

0.8453267162944582